services:

  _defaults:
    autowire: true
    public: true

  App\Module\Common\Domain\Repository\TransactionManagerInterface:
    class: App\Module\Common\Infrastructure\Repository\TransactionManager