version: '2'

services:
  nginx:
    build:
      context: docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.0"
      PHP_IDE_CONFIG: "serverName=architecture-company"
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28