default:
  autoload:
    '': '%paths.base%'
  suites:
    default:
      contexts:
        - behatch:context:json
        - behatch:context:rest
        - Behat\MinkExtension\Context\MinkContext
    apartment_module:
      paths: [ '%paths.base%/../../../src/Module/Apartment/Tests/Behat/features' ]
      contexts:
        - App\Module\Apartment\Tests\Behat\Contexts\ApartmentContext
        - behatch:context:json
        - behatch:context:rest
        - Behat\MinkExtension\Context\MinkContext
      tags: "@apartment_module"

  extensions:
    FriendsOfBehat\SymfonyExtension:
      kernel:
        environment: test
    Behatch\Extension: ~
    Behat\MinkExtension:
      sessions:
        default:
          symfony: ~