services:

  _defaults:
    autowire: true
    public: true

  ac.apartment.use_case.apartment.create_apartment:
    class: App\Module\Apartment\Application\Application\UseCase\Apartment\CreateApartment\CreateApartment
